name: Stable release
on:
  push:
    branches: [ main, update/clean-ci ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: install node dependencies
      run: npm install
     
    - name: run dist build
      run: npm run dist

    - name: Remove innecesary files and directories
      run: rm -rf .gitignore temp app/styles/src src node_modules bin environment.js package.json package-lock.json styles.config tsconfig.json .github 
      
    - name: Check the output
      run: ls -lha .

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4.3.0
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: . # The folder the action should deploy.
